### ISSUE TITLE
openid 2.0

### ISSUE THREAD

**Issue by gertcuykens** [caprazzo/couchdb-openid#1]
When can we expect a update pleas :)

**Comment by caprazzo** [comment]
Hi.

I've not been working on the project for some time and I don't expect to go back to it any time soon. Lots of new things keep coming up and I have little time on my hands :(

Feel free to branch the repo and if you make any good changes I'll be happy to pull from it, or add you to contributors of this project. I may be able to help you a bit, but I can't promise.

Good luck
-teo
